### ISSUE TITLE
Error with C linkage

### ISSUE THREAD

**Issue by JLBicho** [JLBicho/theta_driver#1]
Solve the issue with C linkage:

`In file included from /opt/ros/foxy/include/class_loader/class_loader_core.hpp:57,
                 from /opt/ros/foxy/include/class_loader/class_loader.hpp:55,
                 from /opt/ros/foxy/include/rclcpp_components/register_node_macro.hpp:18,
                 from /home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp:257:
/opt/ros/foxy/include/class_loader/meta_object.hpp: At global scope:
/opt/ros/foxy/include/class_loader/meta_object.hpp:162:1: error: template with C linkage
  162 | template<class B>
      | ^~~~~~~~
In file included from /home/jose/theta_z1_ws/src/theta_driver/include/theta_driver/theta_driver_lib.hpp:11,
                 from /home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp:1:
/home/jose/theta_z1_ws/src/theta_driver/3rd/libuvc-theta-sample/gst/thetauvc.h:37:1: note: ‘extern "C"’ linkage started here
   37 | extern "C" {
      | ^~~~~~~~~~
In file included from /opt/ros/foxy/include/class_loader/class_loader_core.hpp:57,
                 from /opt/ros/foxy/include/class_loader/class_loader.hpp:55,
                 from /opt/ros/foxy/include/rclcpp_components/register_node_macro.hpp:18,
                 from /home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp:257:
/opt/ros/foxy/include/class_loader/meta_object.hpp:198:1: error: template with C linkage
  198 | template<class C, class B>
      | ^~~~~~~~
In file included from /home/jose/theta_z1_ws/src/theta_driver/include/theta_driver/theta_driver_lib.hpp:11,
                 from /home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp:1:
/home/jose/theta_z1_ws/src/theta_driver/3rd/libuvc-theta-sample/gst/thetauvc.h:37:1: note: ‘extern "C"’ linkage started here
   37 | extern "C" {
      | ^~~~~~~~~~
`

**Comment by JLBicho** [comment]
Solved the C-linkage problem but now we have a new problem:


`
Starting >>> theta_driver
--- stderr: theta_driver                             
/home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp: In function ‘gboolean theta_driver::gst_bus_callback(GstBus*, GstMessage*, gpointer)’:
/home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp:9:35: warning: unused parameter ‘bus’ [-Wunused-parameter]
    9 | gboolean gst_bus_callback(GstBus* bus, GstMessage* message, gpointer data) {
      |                           ~~~~~~~~^~~
/home/jose/theta_z1_ws/src/theta_driver/src/theta_driver_lib.cpp:9:70: warning: unused parameter ‘data’ [-Wunused-parameter]
    9 | gboolean gst_bus_callback(GstBus* bus, GstMessage* message, gpointer data) {
      |                                                             ~~~~~~~~~^~~~
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_devices':
thetauvc.c:(.text+0x3f): undefined reference to `uvc_find_devices'
/usr/bin/ld: thetauvc.c:(.text+0x76): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0xb1): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x118): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0x124): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x184): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x1d6): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x1f3): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_print_devices':
thetauvc.c:(.text+0x29a): undefined reference to `uvc_perror'
/usr/bin/ld: thetauvc.c:(.text+0x2f4): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x332): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x367): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_device':
thetauvc.c:(.text+0x3fc): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0x428): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x451): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_device_by_serial':
thetauvc.c:(.text+0x523): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x562): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x582): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x59e): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_get_stream_ctrl_format_size':
thetauvc.c:(.text+0x62b): undefined reference to `uvc_get_stream_ctrl_format_size'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_run_streaming':
thetauvc.c:(.text+0x674): undefined reference to `uvc_open'
/usr/bin/ld: thetauvc.c:(.text+0x6d2): undefined reference to `uvc_start_streaming'
/usr/bin/ld: thetauvc.c:(.text+0x6e4): undefined reference to `uvc_close'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_copy_deep'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_app_src_set_caps'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_map'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_pipeline_set_clock'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_init'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_error_free'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_pipeline_get_bus'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_object_unref'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_pipeline_get_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_element_set_state'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_type_check_instance_cast'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_unmap'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_main_loop_quit'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_exit'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_sample_get_buffer'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_main_loop_new'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_signal_connect_data'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_bin_get_by_name'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_caps_new_simple'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_system_clock_obtain'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_stop_streaming'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_parse_launch'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_free'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_bin_get_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_new_allocate'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_mini_object_unref'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_message_parse_error'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_init'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_print'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `_gst_fraction_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_timer_new'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_bus_add_watch'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_is_initialized'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_signal_emit_by_name'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_app_src_get_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_app_sink_pull_sample'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_source_remove'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/theta_driver_node.dir/build.make:171: theta_driver_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/theta_driver_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< theta_driver [2.61s, exited with code 2]

Summary: 0 packages finished [2.68s]
  1 package failed: theta_driver
  1 package had stderr output: theta_driver

`

Search how to correctly link in CMakeList

**Comment by JLBicho** [comment]
`Starting >>> theta_driver
--- stderr: theta_driver                             
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_devices':
thetauvc.c:(.text+0x3f): undefined reference to `uvc_find_devices'
/usr/bin/ld: thetauvc.c:(.text+0x76): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0xb1): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x118): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0x124): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x184): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x1d6): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x1f3): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_print_devices':
thetauvc.c:(.text+0x29a): undefined reference to `uvc_perror'
/usr/bin/ld: thetauvc.c:(.text+0x2f4): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x332): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x367): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_device':
thetauvc.c:(.text+0x3fc): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0x428): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x451): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_device_by_serial':
thetauvc.c:(.text+0x523): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x562): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x582): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x59e): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_get_stream_ctrl_format_size':
thetauvc.c:(.text+0x62b): undefined reference to `uvc_get_stream_ctrl_format_size'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_run_streaming':
thetauvc.c:(.text+0x674): undefined reference to `uvc_open'
/usr/bin/ld: thetauvc.c:(.text+0x6d2): undefined reference to `uvc_start_streaming'
/usr/bin/ld: thetauvc.c:(.text+0x6e4): undefined reference to `uvc_close'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_init'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_exit'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_stop_streaming'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/theta_driver_node.dir/build.make:233: theta_driver_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/theta_driver_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< theta_driver [0.82s, exited with code 2]

Summary: 0 packages finished [0.90s]
  1 package failed: theta_driver
  1 package had stderr output: theta_driver
`

**Comment by ymd-stella** [comment]
When pasting multiple lines of output, enclose them in ```. See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting.

**Comment by JLBicho** [comment]
Thanks for the feedback! I'll do it next time. 

I'm closing the issue as it is now solved. See https://github.com/stella-cv/theta_driver/issues/1#issuecomment-1129644436
